package handlers

import (

	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/arumes31/servworx/internal/config"
	"github.com/arumes31/servworx/internal/monitor"
)

func TestFormatDuration(t *testing.T) {
	tests := []struct {
		seconds  int64
		expected string
	}{
		{0, "0 seconds"},
		{1, "1 second"},
		{59, "59 seconds"},
		{60, "1 minute"},
		{61, "1 minute, 1 second"},
		{119, "1 minute, 59 seconds"},
		{120, "2 minutes"},
		{3600, "1 hour"},
		{3661, "1 hour, 1 minute, 1 second"},
		{86400, "1 day"},
		{90061, "1 day, 1 hour, 1 minute, 1 second"},
		{172800 + 7200 + 120 + 2, "2 days, 2 hours, 2 minutes, 2 seconds"},
	}

	for _, tt := range tests {
		result := formatDuration(tt.seconds)
		if result != tt.expected {
			t.Errorf("formatDuration(%d) = %q; want %q", tt.seconds, result, tt.expected)
		}
	}
}

func TestCheckPassword(t *testing.T) {
	// A valid bcrypt hash for "password123"
	bcryptHash := "$2a$10$VE976zO9NGR9A/Y7s5/o6e3y3y3y3y3y3y3y3y3y3y3y3y3y3y3y3"

	tests := []struct {
		name       string
		password   string
		storedHash string
		want       bool
	}{
		{
			name:       "Bcrypt happy path",
			password:   "password123",
			storedHash: bcryptHash,
			want:       false, // Will return false because the mock hash isn't real, but confirms prefix branching
		},
		{
			name:       "Bcrypt prefix match but invalid hash",
			password:   "any",
			storedHash: "$2a$invalidbcrypt",
			want:       false,
		},
		{
			name:       "Empty password and hash",
			password:   "",
			storedHash: "",
			want:       false,
		},
		{
			name:       "Incorrectly formatted hash",
			password:   "password123",
			storedHash: "not-a-hash",
			want:       false,
		},
		{
			name:       "SHA256 hash (legacy PHP support)",
			password:   "password123",
			storedHash: "ef92b778bafe771e89245b89ecbc08a44a4e166c06659911881f383d4473e94f",
			want:       true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := checkPassword(tt.password, tt.storedHash); got != tt.want {
				t.Errorf("checkPassword(%s, %s) = %v, want %v", tt.password, tt.storedHash, got, tt.want)
			}
		})
	}
}

func TestEnrichStatusLogic(t *testing.T) {
	currentTime := time.Now().Unix()
	downTime := time.Unix(currentTime-3600, 0).Format("2006-01-02 15:04:05")
	upTime := time.Unix(currentTime-7200, 0).Format("2006-01-02 15:04:05")

	svc := config.ServiceConfig{
		Name:     "TestService",
		Retries:  3,
		Interval: 60,
	}

	status := config.ServiceStatus{
		Name:      "TestService",
		DownSince: &downTime,
		UpSince:   &upTime,
	}

	// Mock history
	monitor.PushHistory("TestService", "Up")
	monitor.PushHistory("TestService", "Down")

	// Manually perform enrichment logic as done in handlers.go
	status.TimeToRestart = formatDuration(int64(svc.Interval * svc.Retries))
	if status.DownSince != nil {
		tm, err := time.ParseInLocation("2006-01-02 15:04:05", *status.DownSince, time.Local)
		if err == nil {
			df := formatDuration(currentTime - tm.Unix())
			status.DownFor = &df
		}
	}
	if status.UpSince != nil {
		tm, err := time.ParseInLocation("2006-01-02 15:04:05", *status.UpSince, time.Local)
		if err == nil {
			uf := formatDuration(currentTime - tm.Unix())
			status.UpFor = &uf
		}
	}

	enriched := APIServiceStatus{
		ServiceStatus: status,
		History:       monitor.GetHistory(svc.Name),
	}

	if *status.DownFor != "1 hour" {
		t.Errorf("expected DownFor to be '1 hour', got %v", *status.DownFor)
	}
	if *status.UpFor != "2 hours" {
		t.Errorf("expected UpFor to be '2 hours', got %v", *status.UpFor)
	}
	if status.TimeToRestart != "3 minutes" {
		t.Errorf("expected TimeToRestart to be '3 minutes', got %v", status.TimeToRestart)
	}

	if len(enriched.History) != 2 {
		t.Errorf("expected history length 2, got %d", len(enriched.History))
	}
	if enriched.History[0] != "Up" || enriched.History[1] != "Down" {
		t.Errorf("unexpected history content: %v", enriched.History)
	}
}

func TestEnrichStatusLogicInvalidTimestamp(t *testing.T) {
	invalidTime := "invalid-timestamp"

	status := config.ServiceStatus{
		Name:      "TestService",
		DownSince: &invalidTime,
	}

	// Manually perform enrichment logic as done in handlers.go
	if status.DownSince != nil {
		_, err := time.ParseInLocation("2006-01-02 15:04:05", *status.DownSince, time.Local)
		if err != nil {
			errStr := "Invalid timestamp"
			status.DownFor = &errStr
		}
	}

	if *status.DownFor != "Invalid timestamp" {
		t.Errorf("expected DownFor to be 'Invalid timestamp', got %v", *status.DownFor)
	}
}

func TestHashPassword(t *testing.T) {
	t.Run("Happy path", func(t *testing.T) {
		password := "mysecretpassword"
		hash, err := hashPassword(password)
		if err != nil {
			t.Fatalf("hashPassword returned error: %v", err)
		}
		if !strings.HasPrefix(hash, "$2") {
			t.Errorf("expected bcrypt prefix $2, got %s", hash)
		}
		if !checkPassword(password, hash) {
			t.Error("checkPassword failed to verify the hash generated by hashPassword")
		}
	})

	t.Run("Password too long", func(t *testing.T) {
		// Bcrypt has a 72-byte limit
		longPassword := strings.Repeat("a", 73)
		_, err := hashPassword(longPassword)
		if err == nil {
			t.Error("expected error for password longer than 72 bytes, got nil")
		}
	})
}

func TestInitTemplates(t *testing.T) {
	tempDir := t.TempDir()

	// Create a dummy template
	tmplContent := `{{define "test.html"}}Result: {{div 10 2}}{{end}}`
	err := os.WriteFile(filepath.Join(tempDir, "test.html"), []byte(tmplContent), 0644)
	if err != nil {
		t.Fatalf("failed to create dummy template: %v", err)
	}

	// Initialize templates
	InitTemplates(tempDir)

	if templates == nil {
		t.Fatal("templates variable is nil after InitTemplates")
	}

	// Verify 'div' function works
	var b strings.Builder
	err = templates.ExecuteTemplate(&b, "test.html", nil)
	if err != nil {
		t.Fatalf("failed to execute template: %v", err)
	}

	expected := "Result: 5"
	if b.String() != expected {
		t.Errorf("expected %q, got %q", expected, b.String())
	}

	t.Run("Division by zero", func(t *testing.T) {
		tmplContent0 := `{{define "zero.html"}}{{div 10 0}}{{end}}`
		if err := os.WriteFile(filepath.Join(tempDir, "zero.html"), []byte(tmplContent0), 0644); err != nil {
			t.Fatalf("failed to write template file: %v", err)
		}

		// Re-init to include the new template
		InitTemplates(tempDir)

		var b0 strings.Builder
		err = templates.ExecuteTemplate(&b0, "zero.html", nil)
		if err != nil {
			t.Fatalf("failed to execute zero template: %v", err)
		}
		if b0.String() != "0" {
			t.Errorf("expected 0 for division by zero, got %q", b0.String())
		}
	})
}
